apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
          
          
          
hulk@Azure:~/Hulk$ kubectl create -f statefulset.yml
service/nginx created
statefulset.apps/web created
ranjith@Azure:~/Hulk$ kubectl scale statefulset web --replicas=3
statefulset.apps/web scaled
ranjith@Azure:~/Hulk$ kubectl get statefulset
NAME   READY   AGE
web    2/3     2m26s
ranjith@Azure:~/Hulk$ kubectl get statefulset
NAME   READY   AGE
web    2/3     2m30s
ranjith@Azure:~/Hulk$ kubectl get statefulset
NAME   READY   AGE
web    3/3     4m12s
